csctapi: Include missing header to fix a warning when building for sh4.
There is a missing include which results in the following warning being
generated when compiling for sh4:
  ifd_sci.c: In function ‘Sci_Reset’:
  ifd_sci.c:51: warning: implicit declaration of function ‘IO_Serial_Read’