minilzo: Disable internal checks because they cause build errors.
This fixes:
{{{
  LINK   ../archiv/oscam-svn8403-fritz33xx-webif.debug
  build/mips-linux-uclibc/minilzo/minilzo.o: In function `_lzo_config_check':
  minilzo.c:(.text+0x678): undefined reference to `__clzsi2'
  collect2: ld returned 1 exit status
}}}

This is the same commit as r8404.